version: "3.8"

services:
  app:
    build: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/urlbase?autoReconnect=true&useSSL=false
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
      image: mysql:5.7
      ports:
        - 3307:3306
      environment:
        - MYSQL_ROOT_PASSWORD=passwordWOW12!!@@
        - MYSQL_DATABASE=urlbase

